name:  Test 

on: 
  workflow_call:
  workflow_dispatch:


jobs: 
  Build-Test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./CSVPortable/
    steps:
      - uses: actions/checkout@v2
      - name: Setup .Net Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: |
            6.0.x
      - name: Build
        run: dotnet build .  --warnaserror
      - name: Test
        run: dotnet test .  --configuration --no-build
